
-- MySQL Script generated by MySQL Workbench
-- Mon Jan 23 17:17:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProgettoISPW
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProgettoISPW` ;

-- -----------------------------------------------------
-- Schema ProgettoISPW
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProgettoISPW` DEFAULT CHARACTER SET utf8 ;
USE `ProgettoISPW` ;

-- -----------------------------------------------------
-- Table `ProgettoISPW`.`Sticker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoISPW`.`Sticker` ;

CREATE TABLE IF NOT EXISTS `ProgettoISPW`.`Sticker` (
  `idSticker` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `StickerURL` VARCHAR(100) NOT NULL,
  `Status` TINYINT NOT NULL,
  PRIMARY KEY (`idSticker`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoISPW`.`Achievement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoISPW`.`Achievement` ;

CREATE TABLE IF NOT EXISTS `ProgettoISPW`.`Achievement` (
  `idAchievement` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Script` VARCHAR(300) NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  `Status` TINYINT NOT NULL,
  `Reward` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAchievement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoISPW`.`Task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoISPW`.`Task` ;

CREATE TABLE IF NOT EXISTS `ProgettoISPW`.`Task` (
  `idTask` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Script` VARCHAR(300) NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  `Status` TINYINT NOT NULL,
  `Reward` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idTask`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoISPW`.`Card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoISPW`.`Card` ;

CREATE TABLE IF NOT EXISTS `ProgettoISPW`.`Card` (
  `Username` VARCHAR(45) NOT NULL,
  `totalEXP` INT NOT NULL,
  `availableChanges` INT NOT NULL,
  `level` INT NOT NULL,
  `profileImage` VARCHAR(500) NOT NULL,
  `SLOT1` INT NULL,
  `SLOT2` INT NULL,
  `SLOT3` INT NULL,
  `SLOT4` INT NULL,
  `SLOT5` INT NULL,
  `SLOT6` INT NULL,
  `SLOT7` INT NULL,
  `SLOT8` INT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoISPW`.`CurrentTasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoISPW`.`CurrentTasks` ;

CREATE TABLE IF NOT EXISTS `ProgettoISPW`.`CurrentTasks` (
  `idCurrentTasks` INT ,
  `Task` INT ,
  `Scadenza` DATETIME,
  PRIMARY KEY (`idCurrentTasks`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProgettoISPW`.`Coach`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProgettoISPW`.`Coach` ;

CREATE TABLE IF NOT EXISTS `ProgettoISPW`.`Coach` (
`id` INT NOT NULL, 
  `motivationalPhrase` VARCHAR(500) NOT NULL,
  `richiestaMotPhr` TINYINT NULL,
  `prelievoMotPhr` TINYINT NULL,
  `richiestaTask` TINYINT NULL,
  `idToChange` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS MoteeveUser;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'MoteeveUser' IDENTIFIED BY 'Moteeve';

GRANT SELECT, INSERT, TRIGGER ON TABLE `ProgettoISPW`.* TO 'MoteeveUser';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `ProgettoISPW`.* TO 'MoteeveUser';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;